name: Build and Push to Artifact Registry

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-south2
  GAR_LOC: asia-south2-docker.pkg.dev/absolute-video/absolute-video-reg

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY_JSON }}"

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_SA_KEY_JSON }} 
      
      - name: Configure docker for GCP
        run: gcloud auth configure-docker
      
      - name: Rebuild env from guthub secrets
        run: echo ${{ secrets.ENV }} > .env

      - name: Rebuild security from guthub secrets
        run: echo ${{ secrets.GCP_PROJECT_ID }} > security.json 

      - name: Build docker image 
        run:  docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/absolute:latest . 

      - name: Push to Google Container Registry
        run:  docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/absolute:latest 

  deploy-cloud-run:
    needs: build-push-artifact
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
      
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY_JSON }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Deploy to Cloud Run"
        run: |-
          gcloud run deploy absolute-video \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/absolute:latest \
            --platform managed \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --set-env-vars=PROJECT_ID=${{ env.PROJECT_ID }}